import { Configuration } from './configuration';
import { BASE_PATH } from './base';
import { ServiceRunnerApi } from './api';

const token =
  'eyJraWQiOiI5eUErR1RlbjlhVE1IaTN5cTlhTVJMNzhlWnZSQlwvNWtRWThFM0YydkpzST0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2MTNiNTViMC0wMGQxLTcwODMtOTI1Ni1iMWUwNjM5M2Y0MDAiLCJkZXZpY2Vfa2V5IjoidXMtZWFzdC0yXzg3ZjM0MzZhLTgxZGUtNDQ5Mi05YzZkLTI2YmUyY2IxNjIwZSIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX0hWRDJyMWN6aSIsImNsaWVudF9pZCI6Ijc5cXNyNGFmN2pycnNtOGY2bGZpMTJhcWx2Iiwib3JpZ2luX2p0aSI6IjdkMGMwM2I0LTE1ZmYtNDU2YS05YmMwLWRkZDU5OThlMjEyZSIsImV2ZW50X2lkIjoiNTBkZmVmODAtNTJmYy00YTRmLWE0NjgtYjBjZDY5Mzc5NzA3IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsImF1dGhfdGltZSI6MTczMTM1NTg5MSwiZXhwIjoxNzMxMzU5NDkxLCJpYXQiOjE3MzEzNTU4OTEsImp0aSI6ImU2NWYyNWI1LTEwOTctNGFhNC1iZDQwLTlmZWYyMTYwODBjMSIsInVzZXJuYW1lIjoiY2FyZW5zZG9yZiJ9.piV9cf_00k4fcu2K-j2HvVqrwFnjBR-H7F_CxFpK2waTLFmvOhaN6bPmXCyMQla9UVZkWmG6Eu8mGSCB_TwaJFnswQWP5lA2dbVp_2pwNWayCsmy0ymG5OWnVqyWs6nTYckqjMQc-v-bi29UGDFFZ4Xd2WMdutWxO4GAx4unuwfIRrtSnOw5XDZGIZ3A_G00mfXYPWw1ojjStmjkaTFZxqT4YOuZs_5L0NXhiK81VnCxzwQopf3DgxDz57MDvBy7ao0HHpmePaQuImDwCI41LdcEv4lezM9CKnZ2hCrb-5GIuyjmcUVdVIWXzdiU72zIQWy4jheL4eyz_IuPRonYBA';

const configuration = new Configuration({
  basePath: BASE_PATH,
  apiKey: `Bearer ${token}`,
});

const BopmaticClient = new ServiceRunnerApi(configuration);

export default BopmaticClient;
